llm:
  image:
    repository: ghcr.io/ben-wangz/word-voyage-llm
    pullPolicy: Always

frontend:
  image:
    repository: ghcr.io/ben-wangz/word-voyage-frontend
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 31300

backend:
  image:
    repository: ghcr.io/ben-wangz/word-voyage-backend
    pullPolicy: Always
