llm:
  image:
    repository: ghcr.io/ben-wangz/word-voyage-llm

frontend:
  image:
    repository: ghcr.io/ben-wangz/word-voyage-frontend
  service:
    type: NodePort
    nodePort: 31300

backend:
  image:
    repository: ghcr.io/ben-wangz/word-voyage-backend
