{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "word-voyage.credentials.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  jwt-secret: {{ include "word-voyage.credentials.jwtSecret" . | b64enc | quote }}
  openai-base-url: {{ include "word-voyage.credentials.openaiBaseUrl" . | b64enc | quote }}
  openai-api-key: {{ include "word-voyage.credentials.openaiApiKey" . | b64enc | quote }}
  openai-model: {{ include "word-voyage.credentials.openaiModel" . | b64enc | quote }}
{{- end }}
